# Chapter 2 - Coding Our First Neurons



In [1]:
import numpy as np
import matplotlib.pyplot as plt

ONE NEURON

In [2]:
# one neuron with three inputs
# making up inputs and weights
inputs  = [1.0, 2.0, 3]
weights = [0.2, 0.8, -0.5]
bias = 2 # only one value for neuron

# output
output = (inputs[0] * weights[0] + inputs[1] * weights[1] + \
          inputs[2] * weights[2] + bias)

print(output)

2.3


In [3]:
# now, one neuron with four inputs
inputs  = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2 # only one value for neuron

# output
output = (inputs[0] * weights[0] + inputs[1] * weights[1] + \
          inputs[2] * weights[2] + inputs[3] * weights[3] + bias)

print(output)

4.8


LAYER OF NEURONS

In [4]:
# YOU SHOULDN'T USE AUX AS VARIABLE NAMES
# my implementation using only python, not even numpy
def one_layer_mine(inputs, weights, bias):
  outputs = []
  aux = 0

  for b, w_neuron in zip(bias, weights):
    aux = 0
    for inp, w_input in zip(inputs, w_neuron):
      aux += inp * w_input

    aux += b

    outputs.append(aux)

  return outputs

In [5]:
# they did the same implementation as me (i promise i didn't look their function)
def one_layer_book(inputs, weights, biases):
  # Output of current layer
  layer_outputs = []
  # For each neuron
  for neuron_weights, neuron_bias in zip(weights, biases):
    # Zeroed output of given neuron
    neuron_output = 0
    # For each input and weight to the neuron
    for n_input, weight in zip(inputs, neuron_weights):
      # Multiply this input by associated weight
      # and add to the neuron’s output variable
      neuron_output += n_input * weight
    # Add bias
    neuron_output += neuron_bias
    # Put neuron’s result to the layer’s output list
    layer_outputs.append(neuron_output)

  return layer_outputs

In [6]:
# 4 inputs, 3 neurons 
inputs  = [1.0, 2.0, 3.0, 2.5]

weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

weights = [weights1, weights2, weights3]

bias1 = 2
bias2 = 3
bias3 = 0.5

bias = [bias1, bias2, bias3]


print(one_layer_mine(inputs, weights, bias))
print(one_layer_book(inputs, weights, bias))

[4.8, 1.21, 2.385]
[4.8, 1.21, 2.385]


# Tensors, Arrays and Vectors

# Definition of homologous
An homologous list/array is when each element inside the list/array has the same dimensions. An array must always be homologous, but a list can be non homologous.

In [13]:
# examples
# homologous (h) list of lists (lol)
h_lol = [[1, 2], [3, 4]]
# non homologous (h) list of lists (lol)
nh_lol = [[1, 2, 3], [4, 5]]

# homologous array
h_arr = np.array([[1, 2], [3, 4]])
print(type(h_arr))
print(h_arr)
# non homologous array
nh_arr = np.array([[1, 2, 3], [4, 5]])
print(type(nh_arr))
print(nh_arr)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
[list([1, 2, 3]) list([4, 5])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  if sys.path[0] == '':


#A single neuron with numpy

In [14]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0

outputs = np.dot(weights, inputs) + bias
print(outputs)

4.8


#A layer of neurons with numpy

In [20]:
inputs = [1.0, 2.0, 3.0, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]
# weights is 3x4, inputs is 4, then np.dot returns a 3x1-dimensional vector
layer_outputs = np.dot(weights, inputs) + biases

print(layer_outputs)

[4.8   1.21  2.385]


#A batch of data
""Often, neural networks expect to take in many ​ samples​ at a time for two reasons. One reason
is that it’s faster to train in batches in parallel processing, and the other reason is that batchesChapter 2 - Coding Our First Neurons - Neural Networks from Scratch in Python
26
help with generalization during training. If you fit (perform a step of a training process) on one
sample at a time, you’re highly likely to keep fitting to that individual sample, rather than
slowly producing general tweaks to weights and biases that fit the entire dataset. Fitting or
training in batches gives you a higher chance of making more meaningful changes to weights
and biases"" Extract from the original book

#Matrix product

#Transposition

In [35]:
# np expand_dims adds a new dimension at the index of the axis
a = [1, 2, 3]

a_arr = np.array(a)
print(a_arr.shape)

a_arr = np.array([a])
print(a_arr.shape)

a_arr2 = np.expand_dims(np.array(a), axis=0)
print(a_arr2.shape)

(3,)
(1, 3)
(1, 3)


In [32]:
#transposing with numpy 
a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T

print(np.dot(a, b))

# np dot performs both vector and matrix multiplication, we only have to transpose
# for matrix multiplication

[[20]]


In [39]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2.0, 3.0, 0.5]

outputs = np.dot(inputs, np.array(weights).T)
print(outputs)
outputs = outputs + biases
print(outputs)

[[ 2.8   -1.79   1.885]
 [ 6.9   -4.81  -0.3  ]
 [-0.59  -1.949 -0.474]]
[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
